# Generated by Django 4.1.7 on 2023-04-14 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0002_alter_comic_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='comic',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='comic',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
